server:
  name: go-sql-hexagonal-architecture-sample
  port: 8080

sql:
  driver: mysql
  data_source_name: root:abcd1234@/masterdata?charset=utf8&parseTime=True&loc=Local

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size

client:
  endpoint:
    url: "http://localhost:8080/users"
    timeout: 10s
  log:
    log: true
    size: size
    status: status
    request: request
    response: response
