server:
  name: go-clean-architecture-sample
  port: 8080

# sql:
#   driver: postgres
#   data_source_name: host=peanut.db.elephantsql.com port=5432 user=yhjnkfrf dbname=yhjnkfrf sslmode=require password=HJ2Z7WiHxBzRKl5e8To_fcIko-i93wda

sql:
  driver: postgres
  data_source_name: host=tiny.db.elephantsql.com port=5432 user=zmpiefhm dbname=zmpiefhm sslmode=require password=QTcJLcQNRuw-q0AHWcE_i0HagqDucTEC


log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size

client:
  endpoint:
    url: "http://localhost:8080/users"
    timeout: 10s
  log:
    log: true
    size: size
    status: status
    request: request
    response: response
